name: Node.js CI

on:
  push:
    branches: [ "main", "testbranch" ]
  pull_request:
    branches: [ "main", "testbranch" ]
    types: [opened, synchronize]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Get repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci
        
    - run: npm run build --if-present
